<?php

/**
 * @file
 * Adds support for sending SMS messages using the OptIt gateway.
 */
 
 /**
 * Implements hook_gateway_info().
 */
function sms_optit_gateway_info() {
  return array(
    'optit' => array(
      'name' => 'OptIt',
      'configure form' => 'sms_optit_admin_form',
      'receive' => FALSE,
      'send' => 'sms_optit_send',
      'send form' => 'sms_optit_send_form',
    ),
  );
}

/**
 * Admin/settings form.
 */
function sms_optit_admin_form($configuration) {
  $form['sms_optit_username'] = array(
    '#type' => 'textfield',
    '#title' => t('OptIt Account Username'),
    '#description' => t('The OptIt username associated with the Mobile API'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => !empty($configuration['sms_optit_username']) ? $configuration['sms_optit_username'] : '',
  );
  $form['sms_optit_password'] = array(
    '#type' => 'textfield',
    '#title' => t('OptIt Account Password'),
    '#description' => t('The OptIt password associated with the Mobile API account'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => !empty($configuration['sms_optit_password']) ? $configuration['sms_optit_password'] : '',
  );
      $form['sms_optit_keyword'] = array(
    '#type' => 'textfield',
    '#title' => t('Keyword'),
    '#description' => t('The keyword associated with the account'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => !empty($configuration['sms_optit_keyword']) ? $configuration['sms_optit_keyword'] : '',
  );
  $form['sms_optit_keyword_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Keyword ID'),
    '#description' => t('The keyword ID associated with the keyword'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => !empty($configuration['sms_optit_keyword_id']) ? $configuration['sms_optit_keyword_id'] : '',
  );
  return $form;
}

/**
 * Callback for sending messages.
 */
function sms_optit_send($number, $message, $options) {
    $gateway = sms_gateways('gateway', 'optit');
    $config = $gateway['configuration'];
    
    watchdog("message", "<pre>" . print_r($message, true) . "</pre>");

$message_bits = str_split($message, 160 - strlen($config['sms_optit_keyword'] . " "));

foreach($message_bits as $message_bit) {

//Create the connection handle
$curl_conn = curl_init();

$url  = "http://api.optitmobile.com/1/sendmessage.xml";
$postVars = "phone=" . $number . "&keyword_id=". $config['sms_optit_keyword_id'] . "&title=drupal&message=" . $config['sms_optit_keyword'] . " " . $message_bit;

//watchdog("PostVars", print_r($postVars, true));

$username = $config['sms_optit_username']; //username
$password = $config['sms_optit_password']; //password

//watchdog("password", print_r($config['sms_optit_password'], true));
//watchdog("username", print_r($config['sms_optit_username'], true));
//watchdog("keyword_id", print_r($config['sms_optit_keyword_id'], true));
//watchdog("keyword", print_r($config['sms_optit_keyword'], true));


//Set cURL options
curl_setopt($curl_conn, CURLOPT_URL, $url); //URL to connect to
curl_setopt($curl_conn, CURLOPT_POST, 1); //Use POST method
curl_setopt($curl_conn, CURLOPT_POSTFIELDS, $postVars); //Use POST method
curl_setopt($curl_conn, CURLOPT_HTTPAUTH, CURLAUTH_BASIC); //Use basic authentication
curl_setopt($curl_conn, CURLOPT_USERPWD, $username.":".$password); //Set u/p
curl_setopt($curl_conn, CURLOPT_RETURNTRANSFER, 1); //Return the result as string

// Result from querying URL. Will parse as xml
$output = curl_exec($curl_conn);

// close cURL resource.
curl_close($curl_conn);
}

//watchdog("output", print_r($output, true));

$result = array(
'status' => TRUE,
'message' => print_r($output, true),
'variables' => NULL,
);

return $result;
}

function sms_optit_form_sms_user_settings_add_form_alter(&$form, &$form_state) {
  //watchdog("form stuff", "<pre>" . print_r($form, true) . "</pre>");
  $form['#submit'][] = 'sms_optit_sms_submit';
}

function sms_optit_sms_submit($form, &$form_state) {
$number = $form['number']['#value'];
$settings = variable_get('sms_optit_settings');
$keywordId = $settings['sms_optit_keyword_id'];

//Create the connection handle
$curl_conn = curl_init();

$subscribe  = "https://api.optitmobile.com/1/keywords/".$keywordId ."/subscriptions.xml";
$postVars = "phone=".$number;
$username = $settings['sms_optit_username']; //username
$password = $settings['sms_optit_password']; //password


//Set cURL options
curl_setopt($curl_conn, CURLOPT_URL, $subscribe); //URL to connect to
curl_setopt($curl_conn, CURLOPT_POST, 1); //Use POST method
curl_setopt($curl_conn, CURLOPT_POSTFIELDS, $postVars); //Use POST method
curl_setopt($curl_conn, CURLOPT_HTTPAUTH, CURLAUTH_BASIC); //Use basic authentication
curl_setopt($curl_conn, CURLOPT_USERPWD, $username.":".$password); //Set u/p
curl_setopt($curl_conn, CURLOPT_RETURNTRANSFER, 1); //Return the result as string

// Result from querying URL. Will parse as xml
$output = curl_exec($curl_conn);

//watchdog("output", print_r($output, true));

// close cURL resource.
curl_close($curl_conn);

//watchdog("form on submit", "<pre>" . print_r($form, true) . "</pre>");
}

